### ISSUE TITLE
The data structure of the datasets--How do I turn multiple folders of images into pickle files

### ISSUE THREAD

**Issue by laiyingxin2** [VISION-SJTU/RECCE#14]
(RE) root@6fb5978ad687:/RECCE# CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 12345 train.py
/root/miniconda3/envs/xiao_db2/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Using debug mode: False.
********************
Loading dataset: 'FaceForensics'...
Loading data from 'FF++ all' of split 'train' and compression 'c40'
Please wait patiently...
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    trainer = ExpMultiGpuTrainer(config, stage="Train")
  File "/data1/ShivamShrirao/RECCE/trainer/exp_mgpu_trainer.py", line 29, in __init__
    super(ExpMultiGpuTrainer, self).__init__(config, stage)
  File "/data1/ShivamShrirao/RECCE/trainer/abstract_trainer.py", line 38, in __init__
    self._train_settings(model_cfg, data_cfg, config_cfg)
  File "/data1/ShivamShrirao/RECCE/trainer/exp_mgpu_trainer.py", line 62, in _train_settings
    self.train_set = load_dataset(name)(train_options)
  File "/data1/ShivamShrirao/RECCE/dataset/faceforensics.py", line 36, in __init__
    indices = torch.load(indices)
  File "/root/miniconda3/envs/xiao_db2/lib/python3.8/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/xiao_db2/lib/python3.8/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/xiao_db2/lib/python3.8/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
**FileNotFoundError: [Errno 2] No such file or directory: 'path/to/data/train_c40.pickle'**

**Comment by laiyingxin2** [comment]
Can someone send me the pre-processed files，my email is laiyingxin@stu.xmu.edu.cn
